### PR TITLE
rename get_header method to get_action

### PR DESCRIPTION
**Pull request by JettTech**
### Updates
 - renames `get_header` endpoint to `get_action` to align with hdk v0.0.138 new naming conventions

### CODE REVIEW

**Review by zo-el — CHANGES_REQUESTED** [review]
you need to update the version number so that a release can be made

**Comment by JettTech** [comment]
I'm thinking of this as a hot update to the hdk 0.0.138 bump, which already had a version update to v0.0.138.  As this crate follows the hdk version, I think it'd be good to keep this version.  Any reason why not?

**Comment by zo-el** [comment]
Yes, but you cannot release to an already released version. you need to update it to a new version like `0.0.138-patch1`

**Review by zo-el — APPROVED** [review]
Approved and a release has been made.

**Pull request merged**
